version: "3"

services:
  jekyll_custom:
    build: .
<<<<<<< HEAD
    image: montahaee.github.io/-local-docker
    container_name: montahaee.github.io/-local-website
||||||| e72fe18
    image: al-folio-local-docker
    container_name: al-folio-local-website
=======
    image: montahaee.github.io-local-docker
    container_name: montahaee.github.io-local-website
>>>>>>> 7989c3885753f37882fa5b43a6d997ec45e11655
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll